### ISSUE TITLE
Create example useage of GetEntryURL

### ISSUE THREAD

**Issue by jcoyne** [go-openapi/kvstore#2]
I haven't seen any example usage of the urlbuilder code anywhere.  It would be fantastic if you could add one here.  One suggestion is for a Location header on a 201 created response.

**Comment by casualjim** [comment]
I added this to the example. https://github.com/go-openapi/kvstore/blob/master/api/handlers/put_entry.go#L62-L63

**Comment by jcoyne** [comment]
Thanks! That’s super helpful @casualjim!
